# Testing docker

name: Azure DB Emulator

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run E2E from"
        required: false
        default: "main"

jobs:
  docker-install:
    runs-on: windows-latest
    name: Azure DB Emulator
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v3

      # Check out onto desired branch to run e2e tests from
      - name: Checkout branch
        run: git checkout ${{ github.event.inputs.branch }}

      # Install docker
      - name: Check docker version
        run: docker -v
        
      #Pull docker image
      - name: Pull docker image
        run: docker pull mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator
