# Testing docker

name: Azure DB Emulator

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run E2E from"
        required: false
        default: "main"

jobs:
  docker-install:
    runs-on: windows-2019
    name: Azure DB Emulator
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v3

      # Check out onto desired branch to run e2e tests from
      - name: Checkout branch
        run: git checkout ${{ github.event.inputs.branch }}

#       # Install docker
#       - name: Check docker version
#         run: docker -v
        
#       # Pull docker image
#       - name: Pull docker image
#         run: docker pull mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator
        
      # Run docker image
      - name: Run docker image
        run: |
          Write-Host "Launching Cosmos DB Emulator"
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator
          Get-CosmosDbEmulatorStatus
          Microsoft.Azure.Cosmos.Emulator.exe Key

      
#       # Run docker image
#       - name: Run docker image
#         run: |
#           md $env:LOCALAPPDATA\CosmosDBEmulator\bind-mount 2>null
#           docker run --name azure-cosmosdb-emulator --memory 2GB --mount "type=bind,source=$env:LOCALAPPDATA\CosmosDBEmulator\bind-mount,destination=C:\CosmosDB.Emulator\bind-mount" -tty -p 8081:8081 -p 8900:8900 -p 8901:8901 -p 8902:8902 -p 10250:10250 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -p 10255:10255 -p 10256:10256 -p 10350:10350 mcr.microsoft.com/cosmosdb/winsrv2019/azure-cosmos-emulator:latest

#       # Install certs
#       - name: Install cert
#         run: | 
#           cd $env:LOCALAPPDATA\CosmosDBEmulator\bind-mount
#           dir
#           powershell .\importcert.ps1
